version: "3"

services:
  postgres:
    container_name: postgres_container
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    container_name: mongo_container
    build:
      context: ./mongo
      dockerfile: mongo.dockerfile
    volumes:
        - ./mongo/data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api_container
    build:
      context: ./api
      dockerfile: api.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - postgres

  nginx:
    container_name: nginx_container
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    volumes:
      - ./static/:/static
    ports:
      - "88:88"
    depends_on:
      - api